### ISSUE TITLE
Making the tags clickable

### ISSUE THREAD

**Issue by Joshi-Sarthak** [MohamedDanis/opnhub#13]
Currently, the tags are not clickable. Adding a feature where clicking on tags automatically triggers a search would greatly improve the user experience.

Idea: Since only a select number of options can be searched, making these tags a different color will help in identifying them.

![Screenshot (324)](https://github.com/user-attachments/assets/eb1723c7-0f0d-416b-964b-8972d0faf06c)

I would like to work on this issue. Can you please assign it to me under Hacktoberfest?

**Comment by MohamedDanis** [comment]
can you give me each tasks what you are planning?

**Comment by Joshi-Sarthak** [comment]
![Screenshot 2024-10-02 123010](https://github.com/user-attachments/assets/a903921c-a0fa-4519-8dac-a0662dad6919)

1. Make the tags searchable on click.
2. Since only some tags are actually searchable, consider giving them a different color, or possibly inverting the color if it looks good.

Example: The tag 'addition' will do nothing when clicked, but the tag 'hacktoberfest' will trigger a search when clicked

**Comment by MohamedDanis** [comment]
1. You can start the first task
2. need more clarification on second task(like color palette),if possible send a design .

please create a branch with your name and make a pr using template in root folder @Joshi-Sarthak

**Comment by Joshi-Sarthak** [comment]
Regarding point 2, I worked on it, but it didn't look good, so I will be skipping that part.

**Comment by Joshi-Sarthak** [comment]
@MohamedDanis i have raise a PR which has gone unnoticed, can you check it? thanks.

**Comment by MohamedDanis** [comment]
I apologize for not being noticed. I had some doubts about this implementation
