### ISSUE TITLE
[Feature Request] Multi-Language Repository Search on GitHub

### ISSUE THREAD

**Issue by imkeanserna** [MohamedDanis/opnhub#17]
Description:
Easily discover repositories on GitHub by selecting multiple programming languages that suit your project needs. This feature allows users to filter repositories based on their preferred languages, ensuring you find the most relevant projects. Whether you're looking for JavaScript, Python, or any combination of languages, this search tool simplifies the process of exploring the vast GitHub ecosystem.

![image](https://github.com/user-attachments/assets/d3b9e831-27ba-442e-bfc9-18cc957f8569)

**Comment by imkeanserna** [comment]
hi @MohamedDanis, can i work on this feature?

**Comment by MohamedDanis** [comment]
@imkurosaki create a branch with your name and make a pr using the template in root directory
**Remeber to pull the latest code before pushing**
