### ISSUE TITLE
Want to add a filter  by recent to oldest feature 

### ISSUE THREAD

**Issue by sanskriti49** [MohamedDanis/opnhub#18]
I would like to contribute to your project by adding a filter  by recent to oldest feature, which would be helpful for users to find more recent github repos in which they can contribute to. Also, I can add the additional tags for frameworks/libraries like React or Node.js etc.. too!
Please assign me this under hacktober!!

**Comment by sanskriti49** [comment]
could you assign it to me pls?

**Comment by MohamedDanis** [comment]
you can work on recent to old feature, the other feature already assigned to another user
create a branch with your name and make a pr with template from root directory
**Remember to pull the latest code before pushing!!!!**
