### ISSUE TITLE
[Feature Req] Implement Infinite Scrolling with Pagination

### ISSUE THREAD

**Issue by imkeanserna** [MohamedDanis/opnhub#25]
**Description:**
I would like to propose the addition of an infinite scrolling feature combined with pagination to enhance the user experience when browsing through repositories. This feature would allow users to load more content seamlessly as they scroll, improving accessibility to repositories.

**Expected**
When scrolling down 18 cards are loaded at a time as the user scrolls down, with a smooth experience provided by dynamic loading and pagination.

**Comment by imkeanserna** [comment]
@MohamedDanis can i work on this?

**Comment by MohamedDanis** [comment]
Not yet, before that need to work on rate limit and limited respos issue
