### ISSUE TITLE
clicking on issues count should redirect user to the issues page of the repository

### ISSUE THREAD

**Issue by HalfToothed** [MohamedDanis/opnhub#28]
Discription: Currently, the issues count displayed is clickable, but it does not redirect user to anywhere. To improve user experience, this needs to be enhanced so that clicking on the issues count takes the user to the respective repository's GitHub issues page.

![image](https://github.com/user-attachments/assets/e7ae72ed-8be2-47e8-9bbe-d3b7b54ec59d)

**Comment by HalfToothed** [comment]
i am working on this feature, can you please assign it to me

**Comment by MohamedDanis** [comment]
sure, make a pr from template provided

**Comment by HalfToothed** [comment]
hey @MohamedDanis I have generated the PR, please authorize the deployment on vercel

**Comment by MohamedDanis** [comment]
done
