### ISSUE TITLE
Add a "Back to Top" Button to Improve Navigation

### ISSUE THREAD

**Issue by HalfToothed** [MohamedDanis/opnhub#38]
The addition of a "Back to Top" button would enhance the user experience, especially for pages with long content. This feature will allow users to quickly return to the top of the page without manually scrolling.

**Comment by MohamedDanis** [comment]
make a pr from the template provided

**Comment by MohamedDanis** [comment]
@HalfToothed updates?

**Comment by MohamedDanis** [comment]
assigned to @tyagidevansh
