### ISSUE TITLE
Enhancement: Add a "Sort By" button to improve user experience and navigation

### ISSUE THREAD

**Issue by abhi9ab** [MohamedDanis/opnhub#39]
I would like to introduce a feature that enables sorting the repository by either the fork count or stars count. The code by default sorts the repos by stars count. The addition of sort by fork count will enhance the navigation.
This enhancement aims to improve the usability and organization of the repository, making it easier for contributors and users to identify popular and widely-used repositories.

**Comment by MohamedDanis** [comment]
Give a rough design of the sort implementation(like placement for sort button and dropdown). After confirming design, I can assign it to you

**Comment by abhi9ab** [comment]
![opnhub-sort-by](https://github.com/user-attachments/assets/f6dc7952-d706-4f20-86bf-31ae1e0a9162)
![opnhub-sort-by-fork](https://github.com/user-attachments/assets/2cb6e799-0875-458e-9a5e-509f38eb2e49)

I have implemented and tested the functionality. For UI, I have used shadcn select component.

**Comment by MohamedDanis** [comment]
Make a Pr from the template provided in the root directory
