### ISSUE TITLE
When clicked on repo link, the page loads on the same tab 

### ISSUE THREAD

**Issue by 10kumaranurag01** [MohamedDanis/opnhub#5]
Description:
When clicked on a  link of a repository on the home page, the github repository loads on the same tab instead of opening on a new tab. If the repository will open on a new tab the user can always come back on the application tab and open new repositories instead of going back on the same tab.

Steps to Reproduce:
Go to the search bar.
Enter a language name.
Click the search button.
Click on a repository link.

Expected Behavior:
The github repository link should open on a new tab.

Actual Behavior:
The repository open on the same tab.

Screen Recording:
[Screencast from 2024-09-30 19-26-18.webm](https://github.com/user-attachments/assets/325208b5-e3d3-406e-b06e-02b1c6a3244a)

Suggested Fix:
The github repository should open on a new tab

Environment:
Browser: (e.g., Chrome 117)
Operating System: (e.g., Ubuntu 22.04)

**Comment by 10kumaranurag01** [comment]
I can fix this, please assign it to me.

**Comment by Anikesh02** [comment]
Hey @MohamedDanis I can work on this issue. Could you please assign this issue to me?

**Comment by MohamedDanis** [comment]
@10kumaranurag01 please make a branch with your name and make a pr

**Comment by MohamedDanis** [comment]
@Anikesh02 already assigned to other user,  check for other issues. Thank you

**Comment by 10kumaranurag01** [comment]
> @10kumaranurag01 please make a branch with your name and make a pr

Thank you
