### ISSUE TITLE
Light theme and dark theme

### ISSUE THREAD

**Issue by Bharath-KumarReddy** [MohamedDanis/opnhub#8]
Adding Light theme and Dark theme toggle button ,

It enhances the user experience , I will make sure that it is very visible , readable  in both dark , light theme 

assign this , under hacktoberfest_2024 : )

**Comment by MohamedDanis** [comment]
please make a branch with your name and do a pr

**Comment by MohamedDanis** [comment]
for change in ui, do a screen record and post it in the comments of your pr

**Comment by Bharath-KumarReddy** [comment]
HI 
just now resolved this issue once check the PR #11  , merge it and label it under hacktoberfest_2024 : )
