### ISSUE TITLE
Search Button bug

### ISSUE THREAD

**Issue by siddxharth1** [MohamedDanis/opnhub#9]
Currently, when the user clicks the search button, it triggers an API call to fetch data. However, the search button remains clickable even while the data is being fetched. This allows users to click the button multiple times, resulting in multiple API calls being made concurrently. This behavior causes performance issues, unnecessary server load, and can lead to inconsistent data or unintended side effects.

![image](https://github.com/user-attachments/assets/2c4dad84-b959-4e1e-9f97-0f9d6db29138)

I would like to resolve this issue so can you assign this issue to me under Hacktoberfest 2024

**Comment by MohamedDanis** [comment]
please create a branch with your name and make a pr
